version: '2'
services:
  covid19fighters-app:
    image: covid19fighters
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:mysql://covid19fighters-mysql:3306/covid19fighters?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://covid19fighters-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://covid19fighters-elasticsearch:9200
    ports:
      - 8080:8080
  covid19fighters-mysql:
    extends:
      file: mysql.yml
      service: covid19fighters-mysql
  covid19fighters-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: covid19fighters-elasticsearch
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
